name: ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        working-directory: North-Star
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install -e Src/backend

      - name: Run tests
        working-directory: North-Star/Src/backend
        env:
          ENV: test
          AUTH_BYPASS: "false"
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing --junitxml=pytest-junit.xml

      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: North-Star/Src/backend/pytest-junit.xml
