name: ci
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run tests
        env:
          APP_ENV: ci
          AUTH_BYPASS: "false"
          # Add any other env your app needs to start
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing --junitxml=pytest-junit.xml

      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: pytest-junit.xml
